/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedCenterRouteImport } from './routes/_authenticated/center'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedTeacherRouteRouteImport } from './routes/_authenticated/teacher/route'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher/index'
import { Route as AuthenticatedTeacherAttendanceRouteImport } from './routes/_authenticated/teacher/attendance'
import { Route as AuthenticatedTeacherBoardRouteImport } from './routes/_authenticated/teacher/board'
import { Route as AuthenticatedTeacherClassesRouteImport } from './routes/_authenticated/teacher/classes'
import { Route as AuthenticatedTeacherContentRouteImport } from './routes/_authenticated/teacher/content'
import { Route as AuthenticatedTeacherLessonsRouteImport } from './routes/_authenticated/teacher/lessons'
import { Route as AuthenticatedTeacherPaymentsRouteImport } from './routes/_authenticated/teacher/payments'
import { Route as AuthenticatedTeacherProfileRouteImport } from './routes/_authenticated/teacher/profile'
import { Route as AuthenticatedTeacherStudentsRouteImport } from './routes/_authenticated/teacher/students'
import { Route as AuthenticatedTeacherStudentsStudentIdRouteImport } from './routes/_authenticated/teacher/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCenterRoute = AuthenticatedCenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherRouteRoute =
  AuthenticatedTeacherRouteRouteImport.update({
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherAttendanceRoute =
  AuthenticatedTeacherAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherBoardRoute =
  AuthenticatedTeacherBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherClassesRoute =
  AuthenticatedTeacherClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherContentRoute =
  AuthenticatedTeacherContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherLessonsRoute =
  AuthenticatedTeacherLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherPaymentsRoute =
  AuthenticatedTeacherPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherProfileRoute =
  AuthenticatedTeacherProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherStudentsRoute =
  AuthenticatedTeacherStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherStudentsStudentIdRoute =
  AuthenticatedTeacherStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedTeacherStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/center': typeof AuthenticatedCenterRoute
  '/student': typeof AuthenticatedStudentRoute
  '/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/teacher/board': typeof AuthenticatedTeacherBoardRoute
  '/teacher/classes': typeof AuthenticatedTeacherClassesRoute
  '/teacher/content': typeof AuthenticatedTeacherContentRoute
  '/teacher/lessons': typeof AuthenticatedTeacherLessonsRoute
  '/teacher/payments': typeof AuthenticatedTeacherPaymentsRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRouteWithChildren
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/center': typeof AuthenticatedCenterRoute
  '/student': typeof AuthenticatedStudentRoute
  '/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/teacher/board': typeof AuthenticatedTeacherBoardRoute
  '/teacher/classes': typeof AuthenticatedTeacherClassesRoute
  '/teacher/content': typeof AuthenticatedTeacherContentRoute
  '/teacher/lessons': typeof AuthenticatedTeacherLessonsRoute
  '/teacher/payments': typeof AuthenticatedTeacherPaymentsRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/center': typeof AuthenticatedCenterRoute
  '/_authenticated/student': typeof AuthenticatedStudentRoute
  '/_authenticated/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/_authenticated/teacher/board': typeof AuthenticatedTeacherBoardRoute
  '/_authenticated/teacher/classes': typeof AuthenticatedTeacherClassesRoute
  '/_authenticated/teacher/content': typeof AuthenticatedTeacherContentRoute
  '/_authenticated/teacher/lessons': typeof AuthenticatedTeacherLessonsRoute
  '/_authenticated/teacher/payments': typeof AuthenticatedTeacherPaymentsRoute
  '/_authenticated/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/_authenticated/teacher/students': typeof AuthenticatedTeacherStudentsRouteWithChildren
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/teacher'
    | '/app'
    | '/center'
    | '/student'
    | '/teacher/attendance'
    | '/teacher/board'
    | '/teacher/classes'
    | '/teacher/content'
    | '/teacher/lessons'
    | '/teacher/payments'
    | '/teacher/profile'
    | '/teacher/students'
    | '/teacher/'
    | '/teacher/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/center'
    | '/student'
    | '/teacher/attendance'
    | '/teacher/board'
    | '/teacher/classes'
    | '/teacher/content'
    | '/teacher/lessons'
    | '/teacher/payments'
    | '/teacher/profile'
    | '/teacher/students'
    | '/teacher'
    | '/teacher/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/teacher'
    | '/_authenticated/app'
    | '/_authenticated/center'
    | '/_authenticated/student'
    | '/_authenticated/teacher/attendance'
    | '/_authenticated/teacher/board'
    | '/_authenticated/teacher/classes'
    | '/_authenticated/teacher/content'
    | '/_authenticated/teacher/lessons'
    | '/_authenticated/teacher/payments'
    | '/_authenticated/teacher/profile'
    | '/_authenticated/teacher/students'
    | '/_authenticated/teacher/'
    | '/_authenticated/teacher/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/center': {
      id: '/_authenticated/center'
      path: '/center'
      fullPath: '/center'
      preLoaderRoute: typeof AuthenticatedCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/attendance': {
      id: '/_authenticated/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof AuthenticatedTeacherAttendanceRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/board': {
      id: '/_authenticated/teacher/board'
      path: '/board'
      fullPath: '/teacher/board'
      preLoaderRoute: typeof AuthenticatedTeacherBoardRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/classes': {
      id: '/_authenticated/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof AuthenticatedTeacherClassesRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/content': {
      id: '/_authenticated/teacher/content'
      path: '/content'
      fullPath: '/teacher/content'
      preLoaderRoute: typeof AuthenticatedTeacherContentRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/lessons': {
      id: '/_authenticated/teacher/lessons'
      path: '/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof AuthenticatedTeacherLessonsRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/payments': {
      id: '/_authenticated/teacher/payments'
      path: '/payments'
      fullPath: '/teacher/payments'
      preLoaderRoute: typeof AuthenticatedTeacherPaymentsRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/profile': {
      id: '/_authenticated/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof AuthenticatedTeacherProfileRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/students': {
      id: '/_authenticated/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/students/$studentId': {
      id: '/_authenticated/teacher/students/$studentId'
      path: '/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedTeacherStudentsRoute
    }
  }
}

interface AuthenticatedTeacherStudentsRouteChildren {
  AuthenticatedTeacherStudentsStudentIdRoute: typeof AuthenticatedTeacherStudentsStudentIdRoute
}

const AuthenticatedTeacherStudentsRouteChildren: AuthenticatedTeacherStudentsRouteChildren =
  {
    AuthenticatedTeacherStudentsStudentIdRoute:
      AuthenticatedTeacherStudentsStudentIdRoute,
  }

const AuthenticatedTeacherStudentsRouteWithChildren =
  AuthenticatedTeacherStudentsRoute._addFileChildren(
    AuthenticatedTeacherStudentsRouteChildren,
  )

interface AuthenticatedTeacherRouteRouteChildren {
  AuthenticatedTeacherAttendanceRoute: typeof AuthenticatedTeacherAttendanceRoute
  AuthenticatedTeacherBoardRoute: typeof AuthenticatedTeacherBoardRoute
  AuthenticatedTeacherClassesRoute: typeof AuthenticatedTeacherClassesRoute
  AuthenticatedTeacherContentRoute: typeof AuthenticatedTeacherContentRoute
  AuthenticatedTeacherLessonsRoute: typeof AuthenticatedTeacherLessonsRoute
  AuthenticatedTeacherPaymentsRoute: typeof AuthenticatedTeacherPaymentsRoute
  AuthenticatedTeacherProfileRoute: typeof AuthenticatedTeacherProfileRoute
  AuthenticatedTeacherStudentsRoute: typeof AuthenticatedTeacherStudentsRouteWithChildren
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedTeacherRouteRouteChildren: AuthenticatedTeacherRouteRouteChildren =
  {
    AuthenticatedTeacherAttendanceRoute: AuthenticatedTeacherAttendanceRoute,
    AuthenticatedTeacherBoardRoute: AuthenticatedTeacherBoardRoute,
    AuthenticatedTeacherClassesRoute: AuthenticatedTeacherClassesRoute,
    AuthenticatedTeacherContentRoute: AuthenticatedTeacherContentRoute,
    AuthenticatedTeacherLessonsRoute: AuthenticatedTeacherLessonsRoute,
    AuthenticatedTeacherPaymentsRoute: AuthenticatedTeacherPaymentsRoute,
    AuthenticatedTeacherProfileRoute: AuthenticatedTeacherProfileRoute,
    AuthenticatedTeacherStudentsRoute:
      AuthenticatedTeacherStudentsRouteWithChildren,
    AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  }

const AuthenticatedTeacherRouteRouteWithChildren =
  AuthenticatedTeacherRouteRoute._addFileChildren(
    AuthenticatedTeacherRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTeacherRouteRoute: typeof AuthenticatedTeacherRouteRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCenterRoute: typeof AuthenticatedCenterRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTeacherRouteRoute: AuthenticatedTeacherRouteRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCenterRoute: AuthenticatedCenterRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
